
  WITH CTE AS (
    SELECT * FROM xnaud.MSEPMRID  
  )
  SELECT (SELECT RSLT_SEQ FROM CTE WHERE rownum = 1) AS RSLT_SEQ_CTE,
         (SELECT TH2_IPDR_STF_NO FROM CTE) AS TH2_IPDR_STF_NO_CTE
     FROM DUAL 
